root: true
parserOptions:
  project: 'package.json'
extends:
  - airbnb-typescript
  - airbnb-typescript-prettier
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  camelcase: 0
  import/prefer-default-export: 0
  no-useless-constructor: 0
  no-shadow: 0
  max-classes-per-file: 0
  no-param-reassign: 0
  no-return-assign: 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/ban-ts-ignore': 0
  '@typescript-eslint/no-empty-function': 0
  func-names: 0
  import/no-cycle: 0
  '@typescript-eslint/no-unused-vars': 0
  no-unused-expressions: 0
  '@typescript-eslint/no-unused-expressions': 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
env:
  mocha: true
